-- ============================================================
-- DATABASE: GOVERNANCE__PREPROD
-- ============================================================

-- Create Database
CREATE DATABASE GOVERNANCE__PREPROD;

-- ============================================================
-- DATABASE LEVEL GRANTS
-- (Excluding BDH_SF_SVC_AR_GOVERNANCE_DEV_CREATE_OBJECTS & RL_WIZ)
-- ============================================================

GRANT USAGE ON DATABASE GOVERNANCE__PREPROD TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;

GRANT USAGE ON DATABASE GOVERNANCE__PREPROD TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;
GRANT SELECT ON FUTURE TABLES IN DATABASE GOVERNANCE__PREPROD TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;
GRANT SELECT ON FUTURE VIEWS IN DATABASE GOVERNANCE__PREPROD TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;

GRANT USAGE ON DATABASE GOVERNANCE__PREPROD TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE GOVERNANCE__PREPROD TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE GOVERNANCE__PREPROD TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT SELECT ON FUTURE TABLES IN DATABASE GOVERNANCE__PREPROD TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE GOVERNANCE__PREPROD TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE GOVERNANCE__PREPROD TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;

GRANT OWNERSHIP ON DATABASE GOVERNANCE__PREPROD TO ROLE SYSADMIN;


-- ============================================================
-- CREATE 5 SCHEMAS
-- ============================================================

CREATE SCHEMA GOVERNANCE__PREPROD.GOV_CLASSIFICATION;
CREATE SCHEMA GOVERNANCE__PREPROD.GOV_STAGING;
CREATE SCHEMA GOVERNANCE__PREPROD.GOV_MASKING;
CREATE SCHEMA GOVERNANCE__PREPROD.GOV_TAGGING;
CREATE SCHEMA GOVERNANCE__PREPROD.GOV_LOGGING;


-- ============================================================
-- SCHEMA LEVEL GRANTS (Applied to all 5 schemas)
-- ============================================================

-- *** GOV_CLASSIFICATION ***
GRANT USAGE, CREATE FUNCTION, CREATE MASKING POLICY, CREATE TABLE, CREATE TAG, CREATE VIEW, MODIFY ON SCHEMA GOVERNANCE__PREPROD.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;
GRANT USAGE ON SCHEMA GOVERNANCE__PREPROD.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA GOVERNANCE__PREPROD.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT OWNERSHIP ON SCHEMA GOVERNANCE__PREPROD.GOV_CLASSIFICATION TO ROLE SYSADMIN;

-- *** GOV_STAGING ***
GRANT USAGE, CREATE FUNCTION, CREATE MASKING POLICY, CREATE TABLE, CREATE TAG, CREATE VIEW, MODIFY ON SCHEMA GOVERNANCE__PREPROD.GOV_STAGING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;
GRANT USAGE ON SCHEMA GOVERNANCE__PREPROD.GOV_STAGING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA GOVERNANCE__PREPROD.GOV_STAGING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT OWNERSHIP ON SCHEMA GOVERNANCE__PREPROD.GOV_STAGING TO ROLE SYSADMIN;

-- *** GOV_MASKING ***
GRANT USAGE, CREATE FUNCTION, CREATE MASKING POLICY, CREATE TABLE, CREATE TAG, CREATE VIEW, MODIFY ON SCHEMA GOVERNANCE__PREPROD.GOV_MASKING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;
GRANT USAGE ON SCHEMA GOVERNANCE__PREPROD.GOV_MASKING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA GOVERNANCE__PREPROD.GOV_MASKING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT OWNERSHIP ON SCHEMA GOVERNANCE__PREPROD.GOV_MASKING TO ROLE SYSADMIN;

-- *** GOV_TAGGING ***
GRANT USAGE, CREATE FUNCTION, CREATE MASKING POLICY, CREATE TABLE, CREATE TAG, CREATE VIEW, MODIFY ON SCHEMA GOVERNANCE__PREPROD.GOV_TAGGING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;
GRANT USAGE ON SCHEMA GOVERNANCE__PREPROD.GOV_TAGGING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA GOVERNANCE__PREPROD.GOV_TAGGING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT OWNERSHIP ON SCHEMA GOVERNANCE__PREPROD.GOV_TAGGING TO ROLE SYSADMIN;

-- *** GOV_LOGGING ***
GRANT USAGE, CREATE FUNCTION, CREATE MASKING POLICY, CREATE TABLE, CREATE TAG, CREATE VIEW, MODIFY ON SCHEMA GOVERNANCE__PREPROD.GOV_LOGGING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;
GRANT USAGE ON SCHEMA GOVERNANCE__PREPROD.GOV_LOGGING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA GOVERNANCE__PREPROD.GOV_LOGGING TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT OWNERSHIP ON SCHEMA GOVERNANCE__PREPROD.GOV_LOGGING TO ROLE SYSADMIN;
