-- ============================================================
-- DATABASE: GOVERNANCE__DEV
-- Privilege Grants (Excluding CREATE_OBJECTS and RL_WIZ roles)
-- ============================================================

-- 1. BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE
GRANT USAGE ON DATABASE GOVERNANCE__DEV TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;

-- 2. BDH_SF_SVC_AR_GOVERNANCE_DEV_READ
GRANT USAGE ON DATABASE GOVERNANCE__DEV TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;
GRANT SELECT ON FUTURE TABLES IN DATABASE GOVERNANCE__DEV TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;
GRANT SELECT ON FUTURE VIEWS IN DATABASE GOVERNANCE__DEV TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;

-- 3. BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE
GRANT USAGE ON DATABASE GOVERNANCE__DEV TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE GOVERNANCE__DEV TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE GOVERNANCE__DEV TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT SELECT ON FUTURE TABLES IN DATABASE GOVERNANCE__DEV TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE GOVERNANCE__DEV TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE GOVERNANCE__DEV TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;

-- 4. SYSADMIN
GRANT OWNERSHIP ON DATABASE GOVERNANCE__DEV TO ROLE SYSADMIN;

-- ============================================================
-- DATABASE: GOVERNANCE__DEV | SCHEMA: GOV_CLASSIFICATION
-- Privilege Grants (Excluding CREATE_OBJECTS and RL_WIZ roles)
-- ============================================================

-- 1. BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE
GRANT USAGE ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;
GRANT CREATE FUNCTION ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;
GRANT CREATE MASKING POLICY ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;
GRANT CREATE TAG ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;
GRANT CREATE VIEW ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;
GRANT MODIFY ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_MANAGE;

-- 2. BDH_SF_SVC_AR_GOVERNANCE_DEV_READ
GRANT USAGE ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;

-- 3. BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE
GRANT USAGE ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;
GRANT CREATE VIEW ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;

-- 4. SYSADMIN
GRANT OWNERSHIP ON SCHEMA GOVERNANCE__DEV.GOV_CLASSIFICATION TO ROLE SYSADMIN;

-- ============================================================
-- TABLE: GOVERNANCE__DEV.GOV_CLASSIFICATION.CLASSIFICATION_DATA
-- One-time grant for already existing table only
-- (Future tables will inherit automatically via FUTURE grants)
-- ============================================================

-- BDH_SF_SVC_AR_GOVERNANCE_DEV_READ
GRANT SELECT ON TABLE GOVERNANCE__DEV.GOV_CLASSIFICATION.CLASSIFICATION_DATA 
    TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_READ;

-- BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE
GRANT DELETE, INSERT, SELECT, TRUNCATE, UPDATE 
    ON TABLE GOVERNANCE__DEV.GOV_CLASSIFICATION.CLASSIFICATION_DATA 
    TO ROLE BDH_SF_SVC_AR_GOVERNANCE_DEV_WRITE;

-- SYSADMIN
GRANT OWNERSHIP ON TABLE GOVERNANCE__DEV.GOV_CLASSIFICATION.CLASSIFICATION_DATA 
    TO ROLE SYSADMIN;
