USE SCHEMA RETAIL_INTELLIGENCE_DB.RAW;

-- ABT Products Table
CREATE OR REPLACE TABLE ABT_PRODUCTS (
  ID INTEGER NOT NULL,
  NAME VARCHAR(500),
  DESCRIPTION VARCHAR(2000),
  PRICE VARCHAR(50),
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_abt_id PRIMARY KEY (ID)
) COMMENT = 'Raw product data from ABT retailer';

-- BUY Products Table
CREATE OR REPLACE TABLE BUY_PRODUCTS (
  ID INTEGER NOT NULL,
  NAME VARCHAR(500),
  DESCRIPTION VARCHAR(2000),
  MANUFACTURER VARCHAR(200),
  PRICE VARCHAR(50),
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_buy_id PRIMARY KEY (ID)
) COMMENT = 'Raw product data from BUY retailer';

-- Ground Truth Mapping
CREATE OR REPLACE TABLE PRODUCT_MAPPING_TRUTH (
  ABT_ID INTEGER NOT NULL,
  BUY_ID INTEGER NOT NULL,
  CONSTRAINT pk_mapping PRIMARY KEY (ABT_ID, BUY_ID)
) COMMENT = 'Ground truth product matches for validation';

-- Create file format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NULL', 'null', '', '\\N')
  TRIM_SPACE = TRUE;

-- Create stage
CREATE OR REPLACE STAGE RETAIL_STAGE
  FILE_FORMAT = CSV_FORMAT
  COMMENT = 'Stage for uploading product catalog files';